### ISSUE TITLE
Two problems with swc-installation-test-2 for a student on Windows

### ISSUE THREAD

**Issue by embray** [swcarpentry/boot-camps#195]
I had one Windows user at the workshop I'm at now who had some false negatives from swc-installation-test-2.  I ran it myself and was able to reproduce the problems:

I reported the IPython script as found, but the ipython package as not found, even though IPython was working fine, and the install test script was being run with the same python as IPython.

The second was that it reported that it couldn't find a default web browser even though it seemed to successfully open/close tabs in the user's default Chrome.

Haven't had a chance to debug any further.  But they were using a recent Python 3 install of Anaconda.

**Comment by wking** [comment]
This repo is dead, and folks should be using [1,2], although I'm
maintaining the checking scripts in a stand-alone repository [3] for
easier reuse.

On Tue, May 24, 2016 at 01:06:46AM -0700, Erik Bray wrote:
> The second was that it reported that it couldn't find a default web
> browser even though it seemed to successfully open/close tabs in the
> user's default Chrome.

The script should not be opening and closing tabs.  The Chrome check
is setup here [4], which will result in a ‘google-chrome --version’
call.

[1]: https://github.com/swcarpentry/workshop-template
[2]: https://github.com/swcarpentry/workshop-template/tree/gh-pages/setup
[3]: https://github.com/wking/swc-setup-installation-test
[4]: https://github.com/wking/swc-setup-installation-test/blob/74844ea43e4df102d9013eae92d19f7f924ee00b/swc-installation-test-2.py#L778-L779
